[package]
name = "txd"
version = "0.2.0"
authors = ["Andrew Palmer <andrew.pa@outlook.com>"]

[dependencies]
runic = { path = "../runic" }
winit = "0.11"
toml = "0.4"
json = "0.11"
futures = "0.1"
mio = "0.6"
regex = "0.2"

[target.'cfg(windows)'.dependencies]
mio-named-pipes = "0.1"

